### ISSUE TITLE
Agent trajectory visualization in Tensorboard (gifs)

### ISSUE THREAD

**Issue by alex-petrenko** [alex-petrenko/landmark-exploration#3]

**Comment by pelillian** [comment]
Closed, unless we don't want to save the gifs from old episodes

**Comment by alex-petrenko** [comment]
How long are the gif animations? Can we afford the entire episode trajectory or not? (for Montezuma it's up to 4000 frames, this is probably too much)

Also, can you only add the last frame to the gif animation? The observations in Doom have 3 channels (RGB) for the 3 stacked past frames. I want only the last one to be in the gif, so that the animation is grayscale.

**Comment by pelillian** [comment]
OK. Greyscale thing is working

**Comment by pelillian** [comment]
Do you want the animation to only be saved at the final checkpoint?

**Comment by alex-petrenko** [comment]
What do you mean by final checkpoint?
For now, this is purely for training visualization. I just want to open tensorboard and see what the agent is doing immediately, without the need to stop training.

I think the reasonable thing to do is to do it by timer, e.g. save one gif animation every minute or two.
Ideally you should save the most "interesting" trajectory, e.g. the one that acquired highest reward (intrinsic+extrinsic). You can use trajectory buffer to select the appropriate trajectory (from complete_trajectories), but be aware that they are currently being reset after every training epoch.
I think you should first render gif and only then reset the trajectories.

You might need to do everything in a separate thread, as I mentioned on Slack. But be sure that you don't write to the same summary writer from different thread, do everything on the main thread, or create a separate gif summary writer and use it from your worker thread.

**Comment by pelillian** [comment]
The average graph summary time is about 0.7 seconds on my machine.

I had implemented it by steps, but I can make it a timer if you want. Yes, I figured out the complete_trajectories thing and am already rendering before they're reset.

**Comment by alex-petrenko** [comment]
I glanced at the implementation and I think it is good. If it really takes 0.7 seconds, I think we can afford it.
Maybe do something to select a more interesting trajectory (as I described above), and after I test tomorrow we can consider it done.

**Comment by pelillian** [comment]
Cool.

Currently, it's implemented to save the entire trajectory. Do you think I should have a parameter that clips the gif trajectory after a given number of steps?

**Comment by alex-petrenko** [comment]
If the entire trajectory isn't too huge, then the entire trajectory is ok. Otherwise if the events file size grows too quickly, we should limit it.

**Comment by alex-petrenko** [comment]
I think it's good now, with the potential exception of high disc usage. But we can deal with this later.
